spring:
  application:
    name: money-transfer-system
  profiles: 
    active: dev

    
    
#spring.application.name=product-ws

# default profile
#spring.profiles.active=prod

#spring.datasource.url=
#spring.datasource.username=
#spring.datasource.password=