spring:
  application:
    name: 01-spring-hello
  datasource:
    url: jdbc:mysql://localhost:3306/mts
    username: root
    password: Root123$
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 9090
logging:
  pattern:
    console: "%c-[%level]- %d-%m-%n"
    file: "%c-[%level]- %d-%m-%n"
  file:
    name: Applog.log




